// ================= DİLLER =================
const languages = {
    tr: {
        about: 'HAKKIMDA', meb: 'ULUSLAR ARASI MEB ROBOT YARIŞMASI', tubitak: 'TÜBİTAK 2242', robotaksi: 'ROBOTAKSİ BİNEK OTONOM ARAÇ YARIŞMASI',
        robotkol: 'KOSGEB DESTEKLİ ROBOT KOL PROJESİ', plcatolyesi: 'PLC-LOJİK ATÖLYESİ ÇALIŞMALARI', egitmenlik: 'T3 VAKFI DENEYAP ATÖLYELERİ – EĞİTMENLİK', scada: 'KARGO OTOMASYONU PROJESİ',
        clawgraber: 'CLAW GRABBER', bitirme: 'BİTİRME PROJESİ (DÜ-HAS)', cvTitle: 'Özgeçmiş', profileTitle: 'Profil',
        profileDesc: 'Elektronik kart tasarımı, gömülü sistem yazılımı ve otomasyon teknolojilerinde deneyimli; takım çalışmasına yatkın ve yenilikçi çözümler üretmeye odaklı bir mekatronik mühendisiyim.',
        educationTitle: 'Eğitim', duzceUni: 'Düzce Üniversitesi', mechatronics: 'Mekatronik Mühendisliği',
        highSchool: 'İnönü MTAL – Elektrik Teknolojileri<br>2015 – 2019', languagesTitle: 'Diller',
        turkish: 'Türkçe', english: 'İngilizce (A2)', contactTitle: 'İletişim Bilgileri',
        personalFeaturesTitle: 'Kişisel Özellikler', teamwork: 'Takım çalışması ve liderlik',
        newTech: 'Yeni teknolojileri öğrenme ve uygulama', timeMgmt: 'Zaman yönetimi ve planlama',
        workHistoryTitle: 'Çalışma Geçmişi', mavili: 'Mavili Elektronik (Stajyer)', petkom: 'Petkom Yazılım (Stajyer)',
        pektam: 'Pektam Pano (Stajyer)', sunny: 'Sunny Elektronik (Stajyer)', orbiba: 'Orbiba Robotics (Stajyer)',
        sonel: 'Sonel Yazılım – Ar-Ge', t3: 'T3 Vakfı – Eğitmen', skillsTitle: 'Beceriler',
        electronicDesign: 'Elektronik Kart Tasarımı', embedded: 'Gömülü Sistem Yazılımı',
        plc: 'PLC / HMI / SCADA', '3dModeling': '3D Katı Modelleme', certificatesTitle: 'Sertifikalar',
        stm32: 'STM32', freertos: 'FreeRTOS', altium: 'Altium PCB', cProg: 'C Programlama',
        welding: 'Gaz Altı Kaynak (Magwell)', close: 'Kapat', projects: 'Projeler',
        university: '<strong>Düzce Üniversitesi</strong><br>Mekatronik Mühendisliği<br>2021 – 2025 | GNO: 3.38',
        galleryTitle: 'Proje Resimleri',
        viewImages: '<i class="fas fa-images"></i> Resimleri Gör'
    },
    en: {
        about: 'ABOUT', meb: 'INTERNATIONAL MEB ROBOT COMPETITION', tubitak: 'TÜBİTAK 2242', robotaksi: 'ROBOTAXI PASSENGER AUTONOMOUS VEHICLE COMPETITION',
        robotkol: 'KOSGEB SUPPORTED ROBOT ARM PROJECT', plcatolyesi: 'PLC-LOGIC WORKSHOP STUDIES', egitmenlik: 'T3 FOUNDATION DENEYAP WORKSHOPS – INSTRUCTORSHIP', scada: 'CARGO AUTOMATION PROJECT',
        clawgraber: 'CLAW GRABBER', bitirme: 'GRADUATION PROJECT (DÜ-HAS)', cvTitle: 'Resume', profileTitle: 'Profile',
        profileDesc: 'Experienced in electronic board design, embedded system software, and automation technologies; a mechatronics engineer inclined to teamwork and focused on producing innovative solutions.',
        educationTitle: 'Education', duzceUni: 'Düzce University', mechatronics: 'Mechatronics Engineering',
        highSchool: 'İnönü MTAL – Electrical Technologies<br>2015 – 2019', languagesTitle: 'Languages',
        turkish: 'Turkish', english: 'English (A2)', contactTitle: 'Contact Information',
        personalFeaturesTitle: 'Personal Features', teamwork: 'Teamwork and leadership',
        newTech: 'Learning and applying new technologies', timeMgmt: 'Time management and planning',
        workHistoryTitle: 'Work History', mavili: 'Mavili Electronics (Intern)', petkom: 'Petkom Software (Intern)',
        pektam: 'Pektam Panel (Intern)', sunny: 'Sunny Electronics (Intern)', orbiba: 'Orbiba Robotics (Intern)',
        sonel: 'Sonel Software – R&D', t3: 'T3 Foundation – Instructor', skillsTitle: 'Skills',
        electronicDesign: 'Electronic Board Design', embedded: 'Embedded System Software',
        plc: 'PLC / HMI / SCADA', '3dModeling': '3D Solid Modeling', certificatesTitle: 'Certificates',
        stm32: 'STM32', freertos: 'FreeRTOS', altium: 'Altium PCB', cProg: 'C Programming',
        welding: 'Gas Metal Arc Welding (Magwell)', close: 'Close', projects: 'Projects',
        university: '<strong>Düzce University</strong><br>Mechatronics Engineering<br>2021 – 2025 | GPA: 3.38',
        galleryTitle: 'Project Images',
        viewImages: '<i class="fas fa-images"></i> View Images'
    }
};
// ================= PROJE VERİLERİ (RESİM YOLLARI GÜNCELLENDİ) =================
const sections = {
    tr: {
        hakkimda: { year: '', title: '', description: '', images: [] },
        meb: { year: '2017-2018', title: 'Uluslar Arası MEB Robot Yarışması', description: '2017–2018 yıllarında Sivas’ta düzenlenen 18. MEB Uluslararası Robot Yarışması “Hızlı Çizgi İzleyen” kategorisine katıldım.<br>Robotun siyah zemin üzerindeki beyaz çizgiyi otonom olarak en kısa sürede ve minimum hatayla takip etmesi hedeflendi.<br>Bu projede elektronik komponent seçimi, çizgi sensörlerinin belirlenmesi ve yerleşimi, motor sürücü devresi ile gömülü yazılımın geliştirilmesi görevlerini üstlendim.', images: ['assets/projects/meb1.jpg', 'assets/projects/meb2.jpg', 'assets/projects/meb3.jpg'] }, // kendi isimlerini ekle
        tubitak: { year: '2021', title: 'TÜBİTAK 2242', description: 'TÜBİTAK 2242 Yarışması İmalat ve Otomotiv kategorisinde takım olarak beşincilik elde ettik.<br>Projede Bluetooth haberleşme altyapısına sahip Arduino tabanlı kontrol sistemi geliştirilmiş, mekanizma tasarımı yapılmış ve gerekli sensör entegrasyonları gerçekleştirilmiştir.<br>Tasarlanan parçalar 3D baskı yöntemiyle üretilmiş ve sistem, tavana monte edilen raylı yapı üzerinde hareket edebilecek şekilde tasarlanmıştır.<br>Projenin temel amacı; dar alanlarda yer kaybını en aza indirerek, raylı sistem üzerinde yük kaldırma ve çeşitli yardımcı işleri gerçekleştirebilen modüler bir robot kol prototipi geliştirmektir.', images: ['assets/projects/tubitak1.jpg', 'assets/projects/tubitak2.jpg'] },
        robotaksi: { year: '2023-2025', title: 'Robotaksi Binek Otonom Araç Yarışması', description: 'Robotaksi Binek Otonom Araç Yarışması’nın amacı; otonom sürüş kabiliyetlerine sahip, güvenli, verimli ve gerçek şehir senaryolarını simüle edebilen binek araçların tasarlanması ve geliştirilmesidir. Yarışma kapsamında ekipler; algılama, karar verme, kontrol ve araç entegrasyonu gibi disiplinlerde yetkinliklerini ortaya koymaktadır.<br><br>2023 yılında Robotaksi Binek Otonom Araç Yarışması’nda ekibimizle 3.’lük elde ederek En İyi Takım Ruhu ödülünü kazandık. Bu projede aracın elektronik kart tasarımı, elektrik sistemi ve gömülü sistem geliştirmelerinden sorumluydum; sensör ve aktüatör entegrasyonlarını gerçekleştirerek aracın güvenli ve verimli çalışmasını sağladım.<br><br>2024 yılında takım kaptanı olarak, önceki aracımızı hem elektriksel hem de mekanik açıdan baştan tasarlayıp geliştirdik ve buna ek olarak ikinci bir araç ürettik. Projede gömülü sistem yazılımı, elektronik kart tasarımı ve takım organizasyonu görevlerini üstlendim; mekanik çalışmalara da aktif katkı sağladım. Ayrıca Baykar, T.C. Gençlik ve Spor Bakanlığı, Uzay Spor, Ensar Kalıp, Mesan Elektrik ve Düzce Belediyesi ile sponsorluk görüşmeleri yaparak destek sağladım.<br><br>2025 yılında, önceki yıllarda edinilen deneyimler doğrultusunda geliştirilen yeni araç projesinde elektrik ekibinde aktif görev aldım ve mekanik çalışmalara destek sağladım. Bu süreçte Cybertruck tasarım yaklaşımından esinlenilen yeni bir araç tasarlandı; projede gömülü sistem yazılımı ve elektronik kart tasarımı görevlerini yürüttüm.', images: ['assets/projects/robotaksi1.jpg', 'assets/projects/robotaksi2.jpg', 'assets/projects/robotaksi3.jpg'] },
        robotkol: { year: '2023-2024', title: 'KOSGEB Destekli Robot Kol Projesi', description: 'Sonel Yazılım firmasında bir yıl boyunca, KOSGEB destekli bir proje kapsamında ERP entegreli robot kol geliştirilmesinde görev aldım. Proje kapsamında, üretilen parçalar görüntü işleme yöntemleriyle kalite kontrol analizine tabi tutulmuş, uygun bulunan ürünler otomatik olarak algılanarak ERP sistemine stok ve üretim bilgileriyle kaydedilmiş, hatalı ürünler ise yeniden üretim sürecine yönlendirilmiştir.<br>Bu projede robot kol prototipinin üretimi, motor kontrol sistemleri ve gömülü sistem donanım–yazılım geliştirme görevlerinden sorumluydum. Geliştirilen sistem, üretim sürecinde insan müdahalesini azaltarak otomatik kalite kontrol ve stok yönetimi sağlamayı hedeflemiştir.', images: ['assets/projects/robotkol1.jpg', 'assets/projects/robotkol2.jpg'] },
        plcatolyesi: { year: '2024', title: 'PLC-Lojik Atölyesi Çalışmaları', description: 'Düzce Üniversitesi Mekatronik Mühendisliği bölümüne kazandırılan PLC Atölyesi kapsamında; PLC deney setleri, FESTO endüstriyel deney standları ve sıvı seviye kontrol mekanizması üzerinde PLC programlama çalışmalarında aktif olarak görev aldım.<br>Bu çalışmaların yanı sıra, PLC’den bağımsız olarak kullanılan lojik kapı deney setlerinin bakım, onarım ve yenileme süreçlerinde yer aldım. Mevcut deney setlerinde bulunan bozulmuş LED’ler, lojik kapı entegreleri ve dirençler tespit edilerek değiştirilmiş, bağlantılar ve lehimler elden geçirilmiş ve setlerin elektriksel sağlamlık ve fonksiyon kontrolleri gerçekleştirilmiştir. Yapılan çalışmalar sonucunda deney setleri, dijital mantık konularının uygulamalı olarak sorunsuz şekilde işlenebileceği hale getirilmiştir.<br>Gerçekleştirilen bu çalışmalar, öğrencilerin temel elektronik ve dijital mantık prensiplerini güvenli ve doğru şekilde öğrenmelerini sağlamayı amaçlamıştır.', images: ['assets/projects/plcatolyesi1.jpg', 'assets/projects/plcatolyesi2.jpg'] },
        egitmenlik: { year: '2023-2025', title: 'T3 Vakfı Deneyap Atölyeleri – Eğitmenlik', description: 'T3 Vakfı Deneyap Teknoloji Atölyeleri’nde, Robotik ve Kodlama, Elektronik Programlama ve Nesnelerin İnterneti (IoT), İleri Robotik, Nanoteknoloji ve Tasarım ve Üretim alanlarında eğitmenlik yaptım. Deneyap Atölyeleri, öğrencilerin 36 aylık proje temelli eğitim programı kapsamında bu teknoloji alanlarında hem teorik bilgi hem de uygulamalı deneyim kazanmalarını amaçlayan bir eğitim modelidir.<br>Bu süreçte öğrencilerle yürüttüğüm eğitimlerde robotik sistemlerin temel prensipleri, sensör ve aktüatör kullanımı, algoritma tabanlı çözüm geliştirme yöntemleri, mikrodenetleyici programlama ve gömülü sistem entegrasyonu konularına odaklandım. Elektronik programlama ve IoT derslerinde DENEYAP Kart gibi donanımlar aracılığıyla giriş seviyesinden ileri seviye çözümlere kadar elektronik devre elemanlarının kullanımı, sensör verilerinin işlenmesi ve kablosuz iletişim temelli prototiplerin geliştirilmesi üzerine uygulamalı çalışmalar yaptırdım.<br>Robotik ve İleri Robotik içerikli eğitimlerimde, öğrencilere mobil robot tasarımı, kontrol mantıkları, robot kinematiği ve proje geliştirme süreçlerini uygulamalı olarak anlattım; takım tabanlı proje üretimlerine rehberlik ettim. Nanoteknoloji ve Tasarım ve Üretim alanlarında ise öğrencilerin üretim odaklı düşünme ve problem çözme becerilerini geliştirmek için 3D tasarım araçları, 3D yazıcılar ve çeşitli prototipleme ekipmanlarıyla çalıştık. Eğitimler süresince öğrencilerin proje geliştirme, takım çalışması ve kritik düşünme becerilerini artırmak amacıyla teknik rehberlik sağladım ve çıktıları değerlendirdim.', images: ['assets/projects/egitmenlik1.jpg', 'assets/projects/egitmenlik2.jpg'] },
        scada: { year: '2025', title: 'Kargo Otomasyonu Projesi', description: 'SCADA dersi kapsamında verilen uygulama ödevi için kargo otomasyonu konusunu seçtim. Geliştirilen otomasyon sisteminin amacı; gelen kargoların boyutlarının ölçülerek sınıflandırılması, uygun bölmelere yönlendirilmesi ve aynı zamanda kargo sayısının kaydedilerek depo kontrolünün sağlanmasıdır.<br>Bu kapsamda sistem kontrolü için Siemens S7-1200 CPU 1214C DC/DC/DC modeli PLC kullanıldı. Kargo boyutlandırma sürecinde sensörlerden alınan analog verilerin işlenebilmesi amacıyla SM 1231 AI 4x13 Bit analog giriş modülü tercih edildi. PLC programı TIA Portal ortamında geliştirilmiş, sistemin görselleştirilmesi ve test edilmesi amacıyla otomasyon süreci Factory I/O kullanılarak simüle edilmiştir. PLC–SCADA entegrasyonu ile sistemin izlenmesi, kontrol edilmesi ve raporlanması sağlanmıştır.', images: ['assets/projects/scada1.jpg', 'assets/projects/scada2.jpg'] },
        clawgraber: { year: '2025', title: 'Claw Grabber', description: 'Mevcut görsel ve referans tasarımlar incelenerek tersine mühendislik metotları uygulanmış, bu doğrultuda mekanik yapıya sahip bir Claw Grabber mekanizması tasarlanmıştır.', images: ['assets/projects/clawgraber1.jpg', 'assets/projects/clawgraber2.jpg'] },
        bitirme: { year: '2025', title: 'Bitirme Projesi (DÜ-HAS)', description: 'TÜBİTAK 2209-A Üniversite Öğrencileri Araştırma Projeleri Destekleme Programı kapsamında destek almaya hak kazanan ve yürütücülüğünü üstlendiğim, aynı zamanda bitirme projem olan “Üniversite Ortamlarında Hava Savunma Sistemleri Geliştirilebilir mi?” başlıklı araştırma projesi, TÜBİTAK tarafından maddi ve akademik olarak desteklenmiştir.<br>Proje kapsamında Raspberry Pi tabanlı görüntü işleme sistemleri kullanılarak gerçek zamanlı hedef tespiti ve anlık müdahale algoritmaları geliştirilmiştir. Ayrıca sensör entegrasyonu, veri işleme ve otomatik kontrol yaklaşımları ele alınmış; tüm yazılım ve mekanik bileşenlerin tek bir donanım platformu üzerinde entegre şekilde çalışması sağlanmıştır.<br>Bu çalışma, savunma sistemleri simülasyonları ile üniversite ortamında uygulanabilir prototip geliştirme açısından önemli bir mühendislik ve araştırma deneyimi kazandırmıştır.', images: ['assets/projects/bitirme1.jpg', 'assets/projects/bitirme2.jpg'] }
    },
    en: { /* aynı yapıyı İngilizce olarak kopyala, önceki mesajlardaki gibi */ }
};

const els = { /* önceki gibi aynı */ };
// ... (geri kalan script.js kodu aynı kalıyor, sadece images yolları yukarıda güncellendi)
